
# assignment_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID NUMBER STRING TYPEassignment : TYPE ID EQUALS valuevalue : NUMBER\n             | STRING'

_lr_action_items = {'TYPE':([0,],[2,]),'$end':([1,5,6,7,],[0,-1,-2,-3,]),'ID':([2,],[3,]),'EQUALS':([3,],[4,]),'NUMBER':([4,],[6,]),'STRING':([4,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),'value':([4,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assignment","S'",1,None,None,None),
  ('assignment -> TYPE ID EQUALS value','assignment',4,'p_assignment','assignment_parser.py',5),
  ('value -> NUMBER','value',1,'p_value','assignment_parser.py',9),
  ('value -> STRING','value',1,'p_value','assignment_parser.py',10),
]
