
# collections_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA EQUALS ID LBRACE LBRACKET LPAREN NUMBER RBRACE RBRACKET RPAREN STRING\n    declaration : ID EQUALS collection\n    \n    collection : list\n               | tuple\n               | set\n               | dict\n    \n    list : LBRACKET items RBRACKET\n         | LBRACKET RBRACKET\n    \n    tuple : LPAREN items RPAREN\n          | LPAREN RPAREN\n    \n    set : LBRACE items RBRACE\n    \n    dict : LBRACE pairs RBRACE\n         | LBRACE RBRACE\n    \n    items : item\n          | items COMMA item\n    \n    item : STRING\n         | NUMBER\n    \n    pairs : pair\n          | pairs COMMA pair\n    \n    pair : STRING COLON item\n    '

_lr_action_items = {'ID':([0,],[2,]),'$end':([1,4,5,6,7,8,13,18,20,24,26,27,28,],[0,-1,-2,-3,-4,-5,-7,-9,-12,-6,-8,-10,-11,]),'EQUALS':([2,],[3,]),'LBRACKET':([3,],[9,]),'LPAREN':([3,],[10,]),'LBRACE':([3,],[11,]),'RBRACKET':([9,12,14,15,16,31,],[13,24,-13,-15,-16,-14,]),'STRING':([9,10,11,25,29,30,],[15,15,23,15,33,15,]),'NUMBER':([9,10,11,25,30,],[16,16,16,16,16,]),'RPAREN':([10,14,15,16,17,31,],[18,-13,-15,-16,26,-14,]),'RBRACE':([11,14,15,16,19,21,22,23,31,32,34,],[20,-13,-15,-16,27,28,-17,-15,-14,-18,-19,]),'COMMA':([12,14,15,16,17,19,21,22,23,31,32,34,],[25,-13,-15,-16,25,25,29,-17,-15,-14,-18,-19,]),'COLON':([23,33,],[30,30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'collection':([3,],[4,]),'list':([3,],[5,]),'tuple':([3,],[6,]),'set':([3,],[7,]),'dict':([3,],[8,]),'items':([9,10,11,],[12,17,19,]),'item':([9,10,11,25,30,],[14,14,14,31,34,]),'pairs':([11,],[21,]),'pair':([11,29,],[22,32,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> ID EQUALS collection','declaration',3,'p_declaration','collections_parser.py',7),
  ('collection -> list','collection',1,'p_collection','collections_parser.py',13),
  ('collection -> tuple','collection',1,'p_collection','collections_parser.py',14),
  ('collection -> set','collection',1,'p_collection','collections_parser.py',15),
  ('collection -> dict','collection',1,'p_collection','collections_parser.py',16),
  ('list -> LBRACKET items RBRACKET','list',3,'p_list','collections_parser.py',23),
  ('list -> LBRACKET RBRACKET','list',2,'p_list','collections_parser.py',24),
  ('tuple -> LPAREN items RPAREN','tuple',3,'p_tuple','collections_parser.py',31),
  ('tuple -> LPAREN RPAREN','tuple',2,'p_tuple','collections_parser.py',32),
  ('set -> LBRACE items RBRACE','set',3,'p_set','collections_parser.py',39),
  ('dict -> LBRACE pairs RBRACE','dict',3,'p_dict','collections_parser.py',46),
  ('dict -> LBRACE RBRACE','dict',2,'p_dict','collections_parser.py',47),
  ('items -> item','items',1,'p_items','collections_parser.py',53),
  ('items -> items COMMA item','items',3,'p_items','collections_parser.py',54),
  ('item -> STRING','item',1,'p_item','collections_parser.py',63),
  ('item -> NUMBER','item',1,'p_item','collections_parser.py',64),
  ('pairs -> pair','pairs',1,'p_pairs','collections_parser.py',70),
  ('pairs -> pairs COMMA pair','pairs',3,'p_pairs','collections_parser.py',71),
  ('pair -> STRING COLON item','pair',3,'p_pair','collections_parser.py',80),
]
