
# data_types_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN COMPLEX FLOAT INTEGER NONE STRING\n    data_type : INTEGER\n              | FLOAT\n              | STRING\n              | BOOLEAN\n              | COMPLEX\n              | NONE\n    '

_lr_action_items = {'INTEGER':([0,],[2,]),'FLOAT':([0,],[3,]),'STRING':([0,],[4,]),'BOOLEAN':([0,],[5,]),'COMPLEX':([0,],[6,]),'NONE':([0,],[7,]),'$end':([1,2,3,4,5,6,7,],[0,-1,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'data_type':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> data_type","S'",1,None,None,None),
  ('data_type -> INTEGER','data_type',1,'p_data_type','data_types_parser.py',7),
  ('data_type -> FLOAT','data_type',1,'p_data_type','data_types_parser.py',8),
  ('data_type -> STRING','data_type',1,'p_data_type','data_types_parser.py',9),
  ('data_type -> BOOLEAN','data_type',1,'p_data_type','data_types_parser.py',10),
  ('data_type -> COMPLEX','data_type',1,'p_data_type','data_types_parser.py',11),
  ('data_type -> NONE','data_type',1,'p_data_type','data_types_parser.py',12),
]
