
# if_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQ GT ID IF LPAREN LT NE NUMBER RPARENif_statement : IF LPAREN condition RPARENcondition : ID LT NUMBER\n                 | ID GT NUMBER\n                 | ID EQ NUMBER\n                 | ID NE NUMBER'

_lr_action_items = {'IF':([0,],[2,]),'$end':([1,6,],[0,-1,]),'LPAREN':([2,],[3,]),'ID':([3,],[5,]),'RPAREN':([4,11,12,13,14,],[6,-2,-3,-4,-5,]),'LT':([5,],[7,]),'GT':([5,],[8,]),'EQ':([5,],[9,]),'NE':([5,],[10,]),'NUMBER':([7,8,9,10,],[11,12,13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'if_statement':([0,],[1,]),'condition':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> if_statement","S'",1,None,None,None),
  ('if_statement -> IF LPAREN condition RPAREN','if_statement',4,'p_if_statement','if_parser.py',5),
  ('condition -> ID LT NUMBER','condition',3,'p_condition','if_parser.py',9),
  ('condition -> ID GT NUMBER','condition',3,'p_condition','if_parser.py',10),
  ('condition -> ID EQ NUMBER','condition',3,'p_condition','if_parser.py',11),
  ('condition -> ID NE NUMBER','condition',3,'p_condition','if_parser.py',12),
]
