
# loops_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON DEDENT EQ FOR GE GT ID IN INDENT LE LPAREN LT NE NEWLINE NUMBER PLUSEQUALS PRINT RANGE RPAREN STRING WHILE\n    loop_statement : while_loop\n                   | for_loop\n    while_loop : WHILE condition COLON suitefor_loop : FOR ID IN RANGE LPAREN NUMBER RPAREN COLON suitesuite : NEWLINE INDENT statements DEDENT\n    statements : statement\n               | statements statement\n    \n    statement : PRINT STRING NEWLINE\n              | ID PLUSEQUALS NUMBER NEWLINE\n    \n    condition : ID GT NUMBER\n              | ID LT NUMBER\n              | ID GE NUMBER\n              | ID LE NUMBER\n              | ID EQ NUMBER\n              | ID NE NUMBER\n    '

_lr_action_items = {'WHILE':([0,],[4,]),'FOR':([0,],[5,]),'$end':([1,2,3,17,33,42,],[0,-1,-2,-3,-5,-4,]),'ID':([4,5,26,28,29,34,38,41,],[7,8,31,31,-6,-7,-8,-9,]),'COLON':([6,19,20,21,22,23,24,37,],[9,-10,-11,-12,-13,-14,-15,40,]),'GT':([7,],[10,]),'LT':([7,],[11,]),'GE':([7,],[12,]),'LE':([7,],[13,]),'EQ':([7,],[14,]),'NE':([7,],[15,]),'IN':([8,],[16,]),'NEWLINE':([9,35,39,40,],[18,38,41,18,]),'NUMBER':([10,11,12,13,14,15,27,36,],[19,20,21,22,23,24,32,39,]),'RANGE':([16,],[25,]),'INDENT':([18,],[26,]),'LPAREN':([25,],[27,]),'PRINT':([26,28,29,34,38,41,],[30,30,-6,-7,-8,-9,]),'DEDENT':([28,29,34,38,41,],[33,-6,-7,-8,-9,]),'STRING':([30,],[35,]),'PLUSEQUALS':([31,],[36,]),'RPAREN':([32,],[37,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'loop_statement':([0,],[1,]),'while_loop':([0,],[2,]),'for_loop':([0,],[3,]),'condition':([4,],[6,]),'suite':([9,40,],[17,42,]),'statements':([26,],[28,]),'statement':([26,28,],[29,34,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> loop_statement","S'",1,None,None,None),
  ('loop_statement -> while_loop','loop_statement',1,'p_loop_statement','loops_parser.py',7),
  ('loop_statement -> for_loop','loop_statement',1,'p_loop_statement','loops_parser.py',8),
  ('while_loop -> WHILE condition COLON suite','while_loop',4,'p_while_loop','loops_parser.py',13),
  ('for_loop -> FOR ID IN RANGE LPAREN NUMBER RPAREN COLON suite','for_loop',9,'p_for_loop','loops_parser.py',17),
  ('suite -> NEWLINE INDENT statements DEDENT','suite',4,'p_suite','loops_parser.py',21),
  ('statements -> statement','statements',1,'p_statements','loops_parser.py',26),
  ('statements -> statements statement','statements',2,'p_statements','loops_parser.py',27),
  ('statement -> PRINT STRING NEWLINE','statement',3,'p_statement','loops_parser.py',36),
  ('statement -> ID PLUSEQUALS NUMBER NEWLINE','statement',4,'p_statement','loops_parser.py',37),
  ('condition -> ID GT NUMBER','condition',3,'p_condition','loops_parser.py',46),
  ('condition -> ID LT NUMBER','condition',3,'p_condition','loops_parser.py',47),
  ('condition -> ID GE NUMBER','condition',3,'p_condition','loops_parser.py',48),
  ('condition -> ID LE NUMBER','condition',3,'p_condition','loops_parser.py',49),
  ('condition -> ID EQ NUMBER','condition',3,'p_condition','loops_parser.py',50),
  ('condition -> ID NE NUMBER','condition',3,'p_condition','loops_parser.py',51),
]
