
# selection_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON DEDENT ELIF ELSE EQ GE GT ID IF INDENT LE LT NE NEWLINE NUMBER PRINT STRING\n    selection_statement : if_statement\n                        | if_else_statement\n    if_statement : IF condition COLON suite\n    if_else_statement : IF condition COLON suite ELSE COLON suite\n                      | IF condition COLON suite elif_statements ELSE COLON suite\n                      | IF condition COLON suite elif_statements\n    \n    elif_statements : elif_statement\n                    | elif_statements elif_statement\n    elif_statement : ELIF condition COLON suite\n    suite : NEWLINE INDENT statements DEDENT\n    \n    statements : statement\n               | statements statement\n    \n    statement : PRINT STRING NEWLINE\n    \n    condition : ID GT NUMBER\n              | ID LT NUMBER\n              | ID GE NUMBER\n              | ID LE NUMBER\n              | ID EQ NUMBER\n              | ID NE NUMBER\n    '

_lr_action_items = {'IF':([0,],[4,]),'$end':([1,2,3,14,23,24,29,34,37,40,41,],[0,-1,-2,-3,-6,-7,-8,-4,-10,-5,-9,]),'ID':([4,25,],[6,6,]),'COLON':([5,16,17,18,19,20,21,22,28,30,],[7,-14,-15,-16,-17,-18,-19,27,35,36,]),'GT':([6,],[8,]),'LT':([6,],[9,]),'GE':([6,],[10,]),'LE':([6,],[11,]),'EQ':([6,],[12,]),'NE':([6,],[13,]),'NEWLINE':([7,27,35,36,39,],[15,15,15,15,42,]),'NUMBER':([8,9,10,11,12,13,],[16,17,18,19,20,21,]),'ELSE':([14,23,24,29,37,41,],[22,28,-7,-8,-10,-9,]),'ELIF':([14,23,24,29,37,41,],[25,25,-7,-8,-10,-9,]),'INDENT':([15,],[26,]),'PRINT':([26,31,32,38,42,],[33,33,-11,-12,-13,]),'DEDENT':([31,32,38,42,],[37,-11,-12,-13,]),'STRING':([33,],[39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'selection_statement':([0,],[1,]),'if_statement':([0,],[2,]),'if_else_statement':([0,],[3,]),'condition':([4,25,],[5,30,]),'suite':([7,27,35,36,],[14,34,40,41,]),'elif_statements':([14,],[23,]),'elif_statement':([14,23,],[24,29,]),'statements':([26,],[31,]),'statement':([26,31,],[32,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> selection_statement","S'",1,None,None,None),
  ('selection_statement -> if_statement','selection_statement',1,'p_selection_statement','selection_parser.py',7),
  ('selection_statement -> if_else_statement','selection_statement',1,'p_selection_statement','selection_parser.py',8),
  ('if_statement -> IF condition COLON suite','if_statement',4,'p_if_statement','selection_parser.py',13),
  ('if_else_statement -> IF condition COLON suite ELSE COLON suite','if_else_statement',7,'p_if_else_statement','selection_parser.py',18),
  ('if_else_statement -> IF condition COLON suite elif_statements ELSE COLON suite','if_else_statement',8,'p_if_else_statement','selection_parser.py',19),
  ('if_else_statement -> IF condition COLON suite elif_statements','if_else_statement',5,'p_if_else_statement','selection_parser.py',20),
  ('elif_statements -> elif_statement','elif_statements',1,'p_elif_statements','selection_parser.py',31),
  ('elif_statements -> elif_statements elif_statement','elif_statements',2,'p_elif_statements','selection_parser.py',32),
  ('elif_statement -> ELIF condition COLON suite','elif_statement',4,'p_elif_statement','selection_parser.py',40),
  ('suite -> NEWLINE INDENT statements DEDENT','suite',4,'p_suite','selection_parser.py',45),
  ('statements -> statement','statements',1,'p_statements','selection_parser.py',51),
  ('statements -> statements statement','statements',2,'p_statements','selection_parser.py',52),
  ('statement -> PRINT STRING NEWLINE','statement',3,'p_statement','selection_parser.py',61),
  ('condition -> ID GT NUMBER','condition',3,'p_condition','selection_parser.py',67),
  ('condition -> ID LT NUMBER','condition',3,'p_condition','selection_parser.py',68),
  ('condition -> ID GE NUMBER','condition',3,'p_condition','selection_parser.py',69),
  ('condition -> ID LE NUMBER','condition',3,'p_condition','selection_parser.py',70),
  ('condition -> ID EQ NUMBER','condition',3,'p_condition','selection_parser.py',71),
  ('condition -> ID NE NUMBER','condition',3,'p_condition','selection_parser.py',72),
]
