
# set_parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA LBRACE NUMBER RBRACEset_decl : LBRACE RBRACEset_decl : LBRACE members RBRACEmembers : NUMBERmembers : members COMMA NUMBER'

_lr_action_items = {'LBRACE':([0,],[2,]),'$end':([1,3,6,],[0,-1,-2,]),'RBRACE':([2,4,5,8,],[3,6,-3,-4,]),'NUMBER':([2,7,],[5,8,]),'COMMA':([4,5,8,],[7,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'set_decl':([0,],[1,]),'members':([2,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> set_decl","S'",1,None,None,None),
  ('set_decl -> LBRACE RBRACE','set_decl',2,'p_set_decl','set_parser.py',5),
  ('set_decl -> LBRACE members RBRACE','set_decl',3,'p_set_decl_nonempty','set_parser.py',9),
  ('members -> NUMBER','members',1,'p_members','set_parser.py',13),
  ('members -> members COMMA NUMBER','members',3,'p_members_list','set_parser.py',17),
]
